export const assets = {
          SkateAnim0: "Skater_Anim00.png",
          SkateAnim1: "Skater_Anim01.png",
          SkateAnim2: "Skater_Anim02.png",
          SkateAnim3: "Skater_Anim03.png",
          SkateAnim4: "Skater_Anim04.png",
          SkateAnim5: "Skater_Anim05.png",
          SkateAnim6: "Skater_Anim06.png",
          SkateAnim7: "Skater_Anim07.png",
          SkateAnim8: "Skater_Anim08.png",
          SkateAnim9: "Skater_Anim09.png",
          SkateAnim10: "Skater_Anim10.png",
          SkateAnim11: "Skater_Anim11.png",
          SkateAnim12: "Skater_Anim12.png",
          SkateAnim13: "Skater_Anim13.png",
          SkateAnim14: "Skater_Anim14.png",
          SkateAnim15: "Skater_Anim15.png",
          SkateAnim16: "Skater_Anim16.png",
          SkateAnim17: "Skater_Anim17.png",
          SkateAnim18: "Skater_Anim18.png",
          //UI
          B_basic: "Fondo.png",
          B_over: "Fondow.png",
          B_press: "Fondoy.png",
          B_long:  "Fondo2.png",
          B_fondo: "Fondo3.png",
          B_marco: "Recuadro.png",
          //Mosquito
          Mosco1: "mosco0.png",
          Mosco2: "mosco1.png",
          Mosco3: "mosco2.png",
          Mosco4: "mosco3.png",
          Mosco5: "mosco4.png",
          Mosco6: "mosco5.png",
          //Objetos
          Banco1: "Banco.png",
          Banco2: "BancoLargo.png",
          Fuente1: "Fuente25_s.png",
          Pilar1: "Pilar1.png",
          Bicic1: "Bicicletero.png",
          Bola1: "BolaTransito.png",
          Pozo1: "Pozo.png",
          Cartel1: "Cartel.png",
          //Fondos
          Baldosas1: "Baldosas.png",
          Builds1: "Parque.png",
          Builds2: "CasaGobierno.jpg",
          Builds3: "Belgrano.png",
          Asfalto1: "Asfalto.png",
          Cesped1: "Cesped.png",
          //Sounds
          SantaFe1: "Cerveza Santa Fe - Himno (Yo soy de Santa Fe) (320 kbps).mp3",
          SantaFe2: "ParaSiempre.mp3",
          roll: "Rolling.ogg",
          jump: "Jump2.ogg",
          fall: "Jump.ogg",
          land: "Land.ogg",
          flip: "Flip.ogg",
          grind: "Grind.ogg"
};
